#!/bin/sh

if [[ -z $1 || ! -f $1 ]]; then
	echo "Usage: ./05_unique_names [source_file]"
	exit
fi

while read l; do
	if [[ -z $l ]]; then
		continue
	fi
	var=$(echo $l | sed "s/\ *<-\s*.*//"  | sed "s/\]/\\\]/g"| sed "s/\[/\\\[/g" | sed "s/\&/\\\&/g");
	string=$(echo $l | sed "s/^.*<-\ *//" | sed "s/\]/\\\]/g"| sed "s/\[/\\\[/g" | sed "s/\&/\\\&/g");

	if [[ $(cat "$1" | grep -E "^${var}[< ]" | wc -l) -gt 1 ]]; then
		nb=$(cat "$1" | grep -E "^${var}[< ]" | wc -l)
		echo "* duplicates (${nb}) for variable \"${var}\""
		#sed -i "s@${string}@${reg}@g" "$f"
		echo $l >> duplicates
		continue
	fi
	echo $l >> single
	#sed -i "s@${string}@${var}@g" "$f"
done < "$1"

cat ./duplicates | sort > d
mv ./d duplicates
